apiVersion: batch/v1
kind: CronJob
metadata:
  name: stock-data-ingestion
spec:
  schedule: "0 * * * *"  # Run every hour
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: fetch-data
            image: your-dockerhub-username/stock-data-ingestion:latest
          restartPolicy: OnFailure